package Vistas;

import lab1_tp3_directorio.DirectorioTelefonico;

/**
 * @author Equipo 10
 */
public class Frm_TP3_NewJframeMain extends javax.swing.JFrame {

    public static  final DirectorioTelefonico guiaTel = new DirectorioTelefonico();
    
    public Frm_TP3_NewJframeMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp_Escritorio = new javax.swing.JDesktopPane();
        jPanel_Main = new javax.swing.JPanel();
        btn_ClienteNuevo = new javax.swing.JButton();
        btn_BuscarCliente = new javax.swing.JButton();
        btn_BuscarTelefono = new javax.swing.JButton();
        btn_BuscarClienteS = new javax.swing.JButton();
        btn_BorrarCliente = new javax.swing.JButton();
        lbl_BusXtel = new javax.swing.JLabel();
        lbl_BusXape = new javax.swing.JLabel();
        lbl_BusXciudad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Main.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefónica Grupo 10", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 0, 24), new java.awt.Color(153, 204, 255))); // NOI18N

        btn_ClienteNuevo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_ClienteNuevo.setForeground(new java.awt.Color(0, 204, 204));
        btn_ClienteNuevo.setText("CLIENTE NUEVO");
        btn_ClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteNuevoActionPerformed(evt);
            }
        });

        btn_BuscarCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_BuscarCliente.setForeground(new java.awt.Color(0, 204, 204));
        btn_BuscarCliente.setText("BUSCAR CLIENTE");
        btn_BuscarCliente.setToolTipText("Permite ver datos de un Cliente ingresando su línea telefónica");
        btn_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarClienteActionPerformed(evt);
            }
        });

        btn_BuscarTelefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_BuscarTelefono.setForeground(new java.awt.Color(0, 204, 204));
        btn_BuscarTelefono.setText("BUSCAR TELEFONO");
        btn_BuscarTelefono.setToolTipText("Permite ver Líneas telefónicas de un Cliente ingresando su línea Apellido");
        btn_BuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarTelefonoActionPerformed(evt);
            }
        });

        btn_BuscarClienteS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_BuscarClienteS.setForeground(new java.awt.Color(0, 204, 204));
        btn_BuscarClienteS.setText("BUSCAR CLIENTES");
        btn_BuscarClienteS.setToolTipText("Ingresando una Ciudad, verá los Clientes de la zona");
        btn_BuscarClienteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarClienteSActionPerformed(evt);
            }
        });

        btn_BorrarCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_BorrarCliente.setForeground(new java.awt.Color(0, 204, 204));
        btn_BorrarCliente.setText("BORRAR CLIENTE");
        btn_BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarClienteActionPerformed(evt);
            }
        });

        lbl_BusXtel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_BusXtel.setForeground(new java.awt.Color(51, 153, 255));
        lbl_BusXtel.setText("Según Linea Telefónica");

        lbl_BusXape.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_BusXape.setForeground(new java.awt.Color(51, 153, 255));
        lbl_BusXape.setText("Según Apellido");

        lbl_BusXciudad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_BusXciudad.setForeground(new java.awt.Color(51, 153, 255));
        lbl_BusXciudad.setText("Según Ciudad");

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_ClienteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarTelefono)
                    .addComponent(btn_BuscarClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_BusXtel)
                    .addComponent(lbl_BusXape)
                    .addComponent(lbl_BusXciudad))
                .addGap(264, 264, 264))
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_ClienteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_BorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BusXtel)
                .addGap(26, 26, 26)
                .addComponent(btn_BuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BusXape)
                .addGap(22, 22, 22)
                .addComponent(btn_BuscarClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BusXciudad)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jdp_Escritorio.setLayer(jPanel_Main, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_EscritorioLayout = new javax.swing.GroupLayout(jdp_Escritorio);
        jdp_Escritorio.setLayout(jdp_EscritorioLayout);
        jdp_EscritorioLayout.setHorizontalGroup(
            jdp_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
            .addGroup(jdp_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdp_EscritorioLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jdp_EscritorioLayout.setVerticalGroup(
            jdp_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(jdp_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdp_EscritorioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdp_Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jdp_Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteNuevoActionPerformed
        //jdp_Escritorio.removeAll();
        //jdp_Escritorio.repaint();        
        Fri_ClienteNuevo ventClie  = new Fri_ClienteNuevo(); //creo la ventana Cliente        
        ventClie.setVisible(true); //le doy visibilidad a la ventana Cliente
        jdp_Escritorio.add(ventClie); //mi ventana ppal va a contener esta vent de Cliente
        jdp_Escritorio.moveToFront(ventClie);
        
    }//GEN-LAST:event_btn_ClienteNuevoActionPerformed

    private void btn_BuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarTelefonoActionPerformed
        //jdp_Escritorio.removeAll();
        //jdp_Escritorio.repaint();        
        Fri_BuscarTelefono ventBusTel  = new Fri_BuscarTelefono(); //creo la ventana Buscar Telefono        
        ventBusTel.setVisible(true); //le doy visibilidad a la ventana Buscar Telefono
        jdp_Escritorio.add(ventBusTel); //mi ventana ppal va a contener esta vent de Buscar Telefono
        jdp_Escritorio.moveToFront(ventBusTel);
    }//GEN-LAST:event_btn_BuscarTelefonoActionPerformed

    private void btn_BuscarClienteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteSActionPerformed
        //jdp_Escritorio.removeAll();
        //jdp_Escritorio.repaint();        
        Fri_BuscarClienteS ventBusUsers  = new Fri_BuscarClienteS(); //creo la ventana Buscar Clientes        
        ventBusUsers.setVisible(true); //le doy visibilidad a la ventana Buscar Clientes
        jdp_Escritorio.add(ventBusUsers); //mi ventana ppal va a contener esta vent de Buscar Clientes
        jdp_Escritorio.moveToFront(ventBusUsers);
    }//GEN-LAST:event_btn_BuscarClienteSActionPerformed

    private void btn_BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarClienteActionPerformed
        //jdp_Escritorio.removeAll();
        //jdp_Escritorio.repaint();
        Fri_BorrarCliente ventBorrClie  = new Fri_BorrarCliente(); //creo la ventana Borrar Cliente
        ventBorrClie.setVisible(true); //le doy visibilidad a la ventana Borrar Cliente
        jdp_Escritorio.add(ventBorrClie); //mi ventana ppal va a contener esta vent de Borrar Cliente
        jdp_Escritorio.moveToFront(ventBorrClie);
    }//GEN-LAST:event_btn_BorrarClienteActionPerformed

    private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
        //jdp_Escritorio.removeAll();
        //jdp_Escritorio.repaint();
        Fri_BuscarCliente ventBusClie  = new Fri_BuscarCliente(); //creo la ventana Buscar Cliente
        ventBusClie.setVisible(true); //le doy visibilidad a la ventana Buscar Cliente
        jdp_Escritorio.add(ventBusClie); //mi ventana ppal va a contener esta vent de Buscar Cliente
        jdp_Escritorio.moveToFront(ventBusClie);
    }//GEN-LAST:event_btn_BuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TP3_NewJframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TP3_NewJframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TP3_NewJframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TP3_NewJframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_TP3_NewJframeMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BorrarCliente;
    private javax.swing.JButton btn_BuscarCliente;
    private javax.swing.JButton btn_BuscarClienteS;
    private javax.swing.JButton btn_BuscarTelefono;
    private javax.swing.JButton btn_ClienteNuevo;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JDesktopPane jdp_Escritorio;
    private javax.swing.JLabel lbl_BusXape;
    private javax.swing.JLabel lbl_BusXciudad;
    private javax.swing.JLabel lbl_BusXtel;
    // End of variables declaration//GEN-END:variables
}
